name: OSV Scanner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
    # checkout code
      - uses: actions/checkout@v3
      
    # Setups GO in the machine
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        
    # Installs and runs OSV scanner
      - name: Installs and runs OSV Scanner
        id: osvscan
        run: |
          go install github.com/google/osv-scanner/cmd/osv-scanner@v1
          export PATH=${PATH}:`go env GOPATH`/bin # Sets PATH environment variable properly
          osv-scanner -r .
